In [9]:
import pandas as pd

df = df.to_sql("sales", conn, if_exists="replace", index=False)

In [10]:
import sqlite3
conn = sqlite3.connect("superstore.db")

In [11]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

    name
0  sales

# What are the Top 5 Products by Revenue?

In [16]:
query = """
SELECT "Product Name", SUM(Sales) AS Total_Revenue
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Revenue DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Revenue
0              Canon imageCLASS 2200 Advanced Copier      61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...      27453.384
2  Cisco TelePresence System EX90 Videoconferenci...      22638.480
3       HON 5400 Series Task Chairs for Big and Tall      21870.576
4         GBC DocuBind TL300 Electric Binding System      19823.479

# Monthly Sales Trend

In [17]:
query2 = """
SELECT strftime('%Y', "Order Date") AS Order_Year,
       strftime('%m', "Order Date") AS Order_Month,
       SUM(Sales) AS Monthly_Sales
FROM sales
GROUP BY Order_Year, Order_Month
ORDER BY Order_Year, Order_Month;
"""

pd.read_sql(query2, conn)

   Order_Year Order_Month  Monthly_Sales
0        2015          01     14205.7070
1        2015          02      4519.8920
2        2015          03     55205.7970
3        2015          04     27906.8550
4        2015          05     23644.3030
5        2015          06     34322.9356
6        2015          07     33781.5430
7        2015          08     27117.5365
8        2015          09     81623.5268
9        2015          10     31453.3930
10       2015          11     77907.6607
11       2015          12     68167.0585
12       2016          01     18066.9576
13       2016          02     11951.4110
14       2016          03     32339.3184
15       2016          04     34154.4685
16       2016          05     29959.5305
17       2016          06     23599.3740
18       2016          07     28608.2590
19       2016          08     36818.3422
20       2016          09     63133.6060
21       2016          10     31011.7375
22       2016          11     75249.3995
23       2016          12     74543.6012
24       2017          01     18542.4910
25       2017          02     22978.8150
26       2017          03     51165.0590
27       2017          04     38679.7670
28       2017          05     56656.9080
29       2017          06     39724.4860
30       2017          07     38320.7830
31       2017          08     30542.2003
32       2017          09     69193.3909
33       2017          10     59583.0330
34       2017          11     79066.4958
35       2017          12     95739.1210
36       2018          01     43476.4740
37       2018          02     19920.9974
38       2018          03     58863.4128
39       2018          04     35541.9101
40       2018          05     43825.9822
41       2018          06     48190.7277
42       2018          07     44825.1040
43       2018          08     62837.8480
44       2018          09     86152.8880
45       2018          10     77448.1312
46       2018          11    117938.1550
47       2018          12     83030.3888

# Revenue by Region

In [18]:
query3 = """
SELECT Region, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query3, conn)

    Region  Total_Sales
0     West  710219.6845
1     East  669518.7260
2  Central  492646.9132
3    South  389151.4590

# Revenue by Customer Segment

In [19]:
query4 = """
SELECT Segment, SUM(Sales) AS Segment_Revenue
FROM sales
GROUP BY Segment
ORDER BY Segment_Revenue DESC;
"""

pd.read_sql(query4, conn)

       Segment  Segment_Revenue
0     Consumer     1.148061e+06
1    Corporate     6.884941e+05
2  Home Office     4.249822e+05

# Average Shipping Time by Ship Mode

In [20]:
query5 = """
SELECT "Ship Mode", AVG("Shipping Days") AS Avg_Shipping_Time
FROM sales
GROUP BY "Ship Mode"
ORDER BY Avg_Shipping_Time DESC;
"""

pd.read_sql(query5, conn)

        Ship Mode  Avg_Shipping_Time
0  Standard Class           5.008363
1    Second Class           3.249211
2     First Class           2.179214
3        Same Day           0.044610

# Top 10 Customers by Revenue

In [21]:
query6 = """
SELECT "Customer Name", SUM(Sales) AS Customer_Revenue
FROM sales
GROUP BY "Customer Name"
ORDER BY Customer_Revenue DESC
LIMIT 10;
"""

pd.read_sql(query6, conn)

        Customer Name  Customer_Revenue
0         Sean Miller         25043.050
1        Tamara Chand         19052.218
2        Raymond Buch         15117.339
3        Tom Ashbrook         14595.620
4       Adrian Barton         14473.571
5        Ken Lonsdale         14175.229
6        Sanjit Chand         14142.334
7        Hunter Lopez         12873.298
8        Sanjit Engle         12209.438
9  Christopher Conant         12129.072